### ISSUE TITLE
distinct color for keywords

### ISSUE THREAD

**Issue by corporatepiyush** [sivertsenstian/visualclojure#28]
Is it possible to show clj keywords in different color than default font color of code ?
i think the distinct color for keywords will make more readable

**Comment by sivertsenstian** [comment]
The coloring of keywords is based on the coloring theme that you are using, not this extension.

This is actually now possible with the latest vscode release!

More information here: https://code.visualstudio.com/updates/v1_15#_user-definable-syntax-highlighting-colors

To change the color of all keywords to #ff0000   ![#ff0000](https://placehold.it/15/f03c15/000000?text=+) 
add this to your User Settings:

```json
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "constant.keyword.clojure",
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    }
```
